nota1=3
nota2=5
nota3=6
nota4=4
nota5=8
print((nota1+nota2+nota3+nota4)/4)
notas=[3,5,6,4,8]
print(notas)
notas.append(10)
notas.append(8)
notas.append(5)
print(notas)
print(len(notas))
print(sum(notas))
print(sum(notas)/len(notas))
print(notas[0])
print(notas[len(notas)-1])
print(len(notas))
#tuplas
tupla=(3,4,5)
tupla+=(4,)
print(tupla)
tupla=tupla +(7,)
print(tupla)
#Sets
set_nota=(1,2,3,4,5,5,3)
print(set_nota)
set_nota.add(7)
print(set_nota)
set_nota.add("Valor")
print(set_nota)
